# Generated by Django 4.1.1 on 2022-09-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(max_length=255, verbose_name="Название школы"),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=255, verbose_name="Местонахождение школы"
                    ),
                ),
                ("type", models.CharField(max_length=255, verbose_name="Тип школы")),
            ],
            options={
                "verbose_name": "Школа",
                "verbose_name_plural": "Школы",
            },
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=70, verbose_name="Имя")),
                ("surname", models.CharField(max_length=70, verbose_name="Фамилия")),
                ("email", models.EmailField(max_length=70, verbose_name="Email")),
                (
                    "student_school",
                    models.CharField(max_length=70, verbose_name="Школа"),
                ),
                ("student_class", models.IntegerField(verbose_name="Класс")),
                ("individual_number", models.IntegerField(verbose_name="ИИН")),
                ("phone", models.IntegerField(verbose_name="Телефон")),
                (
                    "password1",
                    models.CharField(max_length=70, null=True, verbose_name="Пароль"),
                ),
                (
                    "image_file",
                    models.ImageField(
                        null=True, upload_to="resource", verbose_name="Фото"
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
            },
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        null=True, upload_to="resource", verbose_name="Фото"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=70, null=True, verbose_name="Имя"),
                ),
                (
                    "surname",
                    models.CharField(max_length=70, null=True, verbose_name="Фамилия"),
                ),
                (
                    "father_name",
                    models.CharField(max_length=70, null=True, verbose_name="Отчество"),
                ),
                (
                    "diploma_specialty",
                    models.CharField(
                        max_length=70,
                        null=True,
                        verbose_name="Специальность по диплому",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        max_length=70, null=True, verbose_name="Образование"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        max_length=70, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=70, null=True, verbose_name="Категория"
                    ),
                ),
                (
                    "work_experience",
                    models.CharField(
                        max_length=70, null=True, verbose_name="Стаж работы"
                    ),
                ),
                (
                    "achievement",
                    models.CharField(
                        default="", max_length=70, verbose_name="Достижения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Учитель",
                "verbose_name_plural": "Учителя",
            },
        ),
    ]
